# Generated by Django 4.1.2 on 2022-11-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Picture",
            new_name="Para",
        ),
    ]
