# Generated by Django 4.1.2 on 2023-04-15 06:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bloghistory",
            managers=[
                ("graph", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="bookmark",
            managers=[
                ("graph", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("graph", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="like",
            managers=[
                ("graph", django.db.models.manager.Manager()),
            ],
        ),
    ]
