# Generated by Django 4.1.2 on 2023-04-09 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_history",
            field=models.ManyToManyField(
                related_name="user_blog_history", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
