# Generated by Django 4.1.2 on 2022-11-07 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_rename_picture_para"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeCat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_like", models.BooleanField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cate_like",
                        to="blog.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_cat_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("category", "owner")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="cat_like",
            field=models.ManyToManyField(
                related_name="user_category_like",
                through="blog.LikeCat",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
