# Generated by Django 4.1.2 on 2022-11-07 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_likecat_category_cat_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likecat",
            name="cat_like",
        ),
        migrations.AlterField(
            model_name="likecat",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cats_like",
                to="blog.category",
            ),
        ),
    ]
