# Generated by Django 4.1.2 on 2023-04-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0003_remove_blog_blog_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_history_throu",
                        to="blog.blog",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blog_history_throu",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_history",
            field=models.ManyToManyField(
                related_name="user_blog_history",
                through="blog.BlogHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
