# Generated by Django 4.1.2 on 2023-02-15 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useruuid",
            name="id",
        ),
        migrations.AlterField(
            model_name="useruuid",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid5,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
