# Generated by Django 4.1.2 on 2023-02-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermessage",
            name="chat",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="UserMessage",
        ),
    ]
